from typing import Protocol


class JiraProvider(Protocol):
    def get_issue(
        self,
        issue_key: str,
        *,
        fields: str | list[str] | None = None,
        expand: str | None = None,
        comment_limit: int = 10,
        properties: list[str] | None = None,
        update_history: bool = True,
    ) -> dict: ...
    def search_issues(
        self,
        jql: str,
        start: int = 0,
        limit: int = 25,
        *,
        fields: str | list[str] | None = None,
        expand: str | None = None,
        start_at: int | None = None,
        projects_filter: list[str] | None = None,
    ) -> dict: ...
    def get_issue_watchers(self, issue_key: str) -> dict: ...
    def add_watcher(self, issue_key: str, user_identifier: str) -> dict | None: ...
    def remove_watcher(self, issue_key: str, username: str) -> dict | None: ...
    def create_issue(self, fields: dict) -> dict: ...
    def create_issues(self, issues: list[dict]) -> list[dict]: ...
    def update_issue(
        self, issue_key: str, fields: dict, *, attachments: list[str] | None = None
    ) -> dict: ...
    def reparent_subtask(self, issue_id: str, parent_key: str) -> None: ...
    def list_issue_links(self, issue_key: str) -> list[dict]: ...
    def create_issue_link(self, data: dict) -> dict | None: ...
    def delete_issue_link(self, link_id: str) -> dict | None: ...
    def get_issue_link_types(self) -> list[dict]: ...
    def create_remote_issue_link(self, issue_key: str, data: dict) -> dict: ...
    def get_remote_issue_link(self, issue_key: str, link_id: str) -> dict: ...
    def list_issue_attachments(self, issue_key: str) -> list[dict]: ...
    def upload_issue_attachment(self, issue_key: str, file_path: str) -> dict: ...
    def download_issue_attachment(
        self, attachment: dict, destination: str, *, issue_key: str
    ) -> dict: ...
    def delete_issue(self, issue_key: str) -> None: ...
    def transition_issue(
        self,
        issue_key: str,
        transition: str,
        *,
        fields: dict | None = None,
        comment: str | None = None,
    ) -> dict: ...
    def get_issue_transitions(self, issue_key: str) -> list[dict]: ...
    def get_create_meta(self, project_key: str, issue_type: str) -> dict: ...
    def search_fields(self, keyword: str, *, limit: int) -> list[dict]: ...
    def get_field_options(
        self,
        field_id: str,
        project_key: str,
        issue_type: str,
        *,
        contains: str | None = None,
        return_limit: int = 50,
    ) -> list[dict]: ...
    def add_comment(
        self, issue_key: str, body: str, visibility: dict[str, str] | None = None
    ) -> dict: ...
    def edit_comment(
        self,
        issue_key: str,
        comment_id: str,
        body: str,
        visibility: dict[str, str] | None = None,
    ) -> dict: ...
    def get_worklogs(self, issue_key: str) -> dict: ...
    def add_worklog(
        self,
        issue_key: str,
        time_spent: str,
        *,
        comment: str | None = None,
        started: str | None = None,
        original_estimate: str | None = None,
        remaining_estimate: str | None = None,
    ) -> dict: ...
    def assign_issue(self, issue_key: str, assignee: str | None) -> dict: ...
    def list_projects(self) -> list[dict]: ...
    def get_project(self, project_key: str) -> dict: ...
    def get_user(self, username: str) -> dict: ...
    def search_users(
        self,
        query: str,
        *,
        project_key: str | None,
        issue_key: str | None,
        limit: int,
    ) -> list[dict]: ...
