from typing import Protocol


class JiraProvider(Protocol):
    def get_issue(self, issue_key: str) -> dict: ...
    def search_issues(self, jql: str, start: int, limit: int) -> list[dict]: ...
    def create_issue(self, fields: dict) -> dict: ...
    def update_issue(self, issue_key: str, fields: dict) -> dict: ...
    def transition_issue(self, issue_key: str, transition: str) -> dict: ...
