from typing import Protocol


class JiraProvider(Protocol):
    def get_issue(self, issue_key: str) -> dict: ...
    def search_issues(self, jql: str, start: int, limit: int) -> dict: ...
    def create_issue(self, fields: dict) -> dict: ...
    def update_issue(self, issue_key: str, fields: dict) -> dict: ...
    def transition_issue(self, issue_key: str, transition: str) -> dict: ...
    def get_issue_transitions(self, issue_key: str) -> list[dict]: ...
    def search_fields(self, query: str) -> list[dict]: ...
    def get_field_options(self, field_id: str, project_key: str, issue_type: str) -> list[dict]: ...
    def list_projects(self) -> list[dict]: ...
    def get_project(self, project_key: str) -> dict: ...
    def get_user(self, username: str) -> dict: ...
    def search_users(self, query: str) -> list[dict]: ...
