COVERAGE_MANIFEST = {
    "jira issue get": "test_jira_issue_round_trip_live",
    "jira issue search": "test_jira_issue_round_trip_live",
    "jira issue create": "test_jira_issue_round_trip_live",
    "jira issue update": "test_jira_issue_round_trip_live",
    "jira issue transition": "test_jira_issue_round_trip_live",
    "jira issue transitions": "test_jira_issue_round_trip_live",
    "jira issue delete": "test_jira_issue_round_trip_live",
    "jira issue batch-create": "test_jira_issue_batch_create_live",
    "jira issue changelog-batch": "test_jira_issue_changelog_batch_rejected_live",
    "jira field search": "test_jira_project_and_metadata_live",
    "jira field options": "test_jira_project_and_metadata_live",
    "jira comment add": "test_jira_issue_round_trip_live",
    "jira comment edit": "test_jira_issue_round_trip_live",
    "jira project list": "test_jira_project_and_metadata_live",
    "jira project get": "test_jira_project_and_metadata_live",
    "jira user get": "test_jira_project_and_metadata_live",
    "jira user search": "test_jira_project_and_metadata_live",
    "confluence page get": "test_confluence_page_round_trip_live",
    "confluence page search": "test_confluence_space_and_search_live",
    "confluence page children": "test_confluence_page_move_and_children_live",
    "confluence page tree": "test_confluence_space_and_search_live",
    "confluence page history": "test_confluence_page_round_trip_live",
    "confluence page diff": "test_confluence_page_round_trip_live",
    "confluence page move": "test_confluence_page_move_and_children_live",
    "confluence page create": "test_confluence_page_round_trip_live",
    "confluence page update": "test_confluence_page_round_trip_live",
    "confluence page delete": "test_confluence_page_round_trip_live",
    "confluence comment list": "test_confluence_comment_round_trip_live",
    "confluence comment add": "test_confluence_comment_round_trip_live",
    "confluence comment reply": "test_confluence_comment_round_trip_live",
    "confluence space list": "test_confluence_space_and_search_live",
    "confluence space get": "test_confluence_space_and_search_live",
    "confluence attachment list": "test_confluence_attachment_round_trip_live",
    "confluence attachment upload": "test_confluence_attachment_round_trip_live",
    "confluence attachment download": "test_confluence_attachment_round_trip_live",
    "bitbucket project list": "test_bitbucket_project_and_repo_queries_live",
    "bitbucket project get": "test_bitbucket_project_and_repo_queries_live",
    "bitbucket repo get": "test_bitbucket_project_and_repo_queries_live",
    "bitbucket repo list": "test_bitbucket_project_and_repo_queries_live",
    "bitbucket repo create": "test_bitbucket_repo_create_live",
    "bitbucket branch list": "test_bitbucket_branch_and_pr_round_trip_live",
    "bitbucket commit build-status": "test_bitbucket_branch_and_pr_round_trip_live",
    "bitbucket pr list": "test_bitbucket_branch_and_pr_round_trip_live",
    "bitbucket pr get": "test_bitbucket_branch_and_pr_round_trip_live",
    "bitbucket pr diff": "test_bitbucket_branch_and_pr_round_trip_live",
    "bitbucket pr build-status": "test_bitbucket_branch_and_pr_round_trip_live",
    "bitbucket pr comment list": "test_bitbucket_branch_and_pr_round_trip_live",
    "bitbucket pr comment get": "test_bitbucket_branch_and_pr_round_trip_live",
    "bitbucket pr comment add": "test_bitbucket_branch_and_pr_round_trip_live",
    "bitbucket pr comment reply": "test_bitbucket_branch_and_pr_round_trip_live",
    "bitbucket pr comment edit": "test_bitbucket_branch_and_pr_round_trip_live",
    "bitbucket pr comment delete": "test_bitbucket_branch_and_pr_round_trip_live",
    "bitbucket pr create": "test_bitbucket_branch_and_pr_round_trip_live",
    "bitbucket pr merge": "test_bitbucket_branch_and_pr_round_trip_live",
    "init": "test_init_single_product_non_interactive_writes_config",
    "update check": "test_update_check_outputs_latest_release_json",
    "update install": "test_update_install_passes_selected_options",
}
