from typing import Protocol


class ConfluenceProvider(Protocol):
    def get_page(self, page_id: str) -> dict: ...
    def create_page(self, *, space_key: str, title: str, body: str) -> dict: ...
    def update_page(self, *, page_id: str, title: str, body: str) -> dict: ...
    def delete_page(self, page_id: str) -> dict: ...
    def list_spaces(self, *, start: int, limit: int) -> dict: ...
    def get_space(self, space_key: str) -> dict: ...
    def list_attachments(self, page_id: str) -> dict: ...
    def upload_attachment(self, page_id: str, file_path: str) -> dict: ...
    def download_attachment(self, attachment_id: str, destination: str) -> dict: ...
